"""deleted education table, added degree and highschool table

Revision ID: 27ffc498c205
Revises: dca5c22c1dc3
Create Date: 2023-09-14 20:43:26.726553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ffc498c205'
down_revision: Union[str, None] = 'dca5c22c1dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
