"""edit skill education language userid column removed unique

Revision ID: 6606882d48a5
Revises: b2b32db7d062
Create Date: 2023-09-03 18:21:22.004898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6606882d48a5'
down_revision: Union[str, None] = 'b2b32db7d062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_education_user_id_key', 'users_education', type_='unique')
    op.drop_constraint('users_languages_user_id_key', 'users_languages', type_='unique')
    op.drop_constraint('users_skills_user_id_key', 'users_skills', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_skills_user_id_key', 'users_skills', ['user_id'])
    op.create_unique_constraint('users_languages_user_id_key', 'users_languages', ['user_id'])
    op.create_unique_constraint('users_education_user_id_key', 'users_education', ['user_id'])
    # ### end Alembic commands ###
