"""deleted education table, added degree and highschool table

Revision ID: cbaf32a08232
Revises: 27ffc498c205
Create Date: 2023-09-14 20:44:06.667811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbaf32a08232'
down_revision: Union[str, None] = '27ffc498c205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_degrees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(), nullable=False),
    sa.Column('field_of_study', sa.String(), nullable=False),
    sa.Column('university', sa.String(), nullable=False),
    sa.Column('degree_year', sa.String(), nullable=False),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_highschools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(), nullable=False),
    sa.Column('school_name', sa.String(), nullable=False),
    sa.Column('certificate_name', sa.String(), nullable=False),
    sa.Column('language_of_study', sa.String(), nullable=False),
    sa.Column('degree_year', sa.String(), nullable=False),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users_education')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_education',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('degree', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('field_of_study', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('university', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('degree_year', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('grade', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_education_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='users_education_pkey')
    )
    op.drop_table('users_highschools')
    op.drop_table('users_degrees')
    # ### end Alembic commands ###
